name: ChadBot
description: An AI Assistant (ChatBot, Image Generator & Language Translator) App Based on ChatGPT developed by Akshat

publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # App Write Database (For dynamically getting API Key)
  appwrite: ^12.0.4

  # iOS Styled Icons
  cupertino_icons: ^1.0.8

  # For using Lottie Animations
  lottie: ^3.1.2

  # For Hive Database (using this version due to less APK size)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Accessing Storage Path
  path_provider: ^2.1.3

  # For State Management
  get: ^4.6.6

  # For Custom Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2

  # For API Call
  http: ^1.2.2

  # For AI Image Generation
  dart_openai: ^5.1.0
  cached_network_image: ^3.3.1

  # Google Gemini AI Integration
  google_generative_ai: ^0.4.3

  # For Google Language Translation
  translator_plus: ^1.0.1

  # For Saving Images to Gallery
  gallery_saver_updated: ^3.0.0

  # For Sharing Images
  share_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^4.0.0

  # For Changing App Icon (commented out)
  # icons_launcher: ^2.1.7

  mockito: ^5.0.0  # Check for the latest version

flutter:
  # Enables Material Design
  uses-material-design: true

  # To add assets to your application, add an assets section
  assets:
    - assets/images/
    - assets/lottie/

  # Uncomment and configure fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
